### PR TITLE
Fixes #29 getUnitFactor should throw an exception if factor is not valid

### LINKED ISSUE #29: getUnitFactor should throw an exception if factor is not valid

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

File: code/auxiliaries/getUnitFactor.m [hunk 1]
```diff
@@ -68,6 +68,10 @@
 
 factor=f_source/f_target;
 
+if ~isfinite(factor)
+    error('The formula %s for unit %s evaluates to a non-finite value (NaN, Inf, -Inf)',unitList(iDim).formula{iU_target},unit_target)
```
Comment (Yuri05) [inline code/auxiliaries/getUnitFactor.m]: @KatrinCoboeken 
THrowing the exception not only for nan but also for +-Inf
